#!/usr/bin/env python3

# Copyright 2022 Trossen Robotics
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#    * Neither the name of the copyright holder nor the names of its
#      contributors may be used to endorse or promote products derived from
#      this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import signal
import sys
from threading import Thread

from geometry_msgs.msg import Pose, Quaternion
from interbotix_moveit_interface_msgs.srv import MoveItPlan
from python_qt_binding.QtCore import Qt
from python_qt_binding.QtGui import QDoubleValidator, QFont
from python_qt_binding.QtWidgets import (
    QApplication,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QSizePolicy,
    QSlider,
    QVBoxLayout,
    QWidget,
    QComboBox,
)
import rclpy
from rclpy.executors import MultiThreadedExecutor
from rclpy.node import Node
from std_srvs.srv import Empty
from tf_transformations import quaternion_from_euler

# There are arbitrarily 10,000 'steps' from one end of a slider bar to the other
RANGE = 10000

# Currently, the VX300 arm has the longest reach around 0.7 meters - so set that as the limit for
# the position slider bars
MAX_ARM_POS = 0.75

# The max rotation a joint can possible do is 3.14 radians - so set that as the limit for the
# orientation slider bars
MAX_ROT_POS = 3.14

class MoveItGUIInterface(Node, QWidget):

    command: MoveItPlan.Request

    def __init__(self, thread: Thread):
        """
        Construct the MoveItGUIInterface object and sets up the GUI layout.
        :param thread: Reference to the thread that spins the executor.
        """
        super().__init__(node_name='moveit_interface_gui')
        QWidget.__init__(self)

        self.thread = thread

    
        # Initialize the service clients and wait for their existence
        self.moveit_planner = self.create_client(MoveItPlan, 'moveit_plan')
        self.clear_markers_service = self.create_client(Empty, 'clear_markers')
        if not (
            self.moveit_planner.wait_for_service(2.0) and
            self.clear_markers_service.wait_for_service(2.0)
        ):
            sys.exit(1)

        # Dictionary that maps an element in the 'param_list' below to a slider value and its
        # associated text box
        self.pose_map = {}

        # An Enum value from the MoveItPlan service
        self.command = MoveItPlan.Request()
        self.command.cmd = MoveItPlan.Request.CMD_NONE

        # Rate at which the infinite loop (in the 'srv_moveit_plan' function) is run
        self.r = self.create_rate(frequency=10)

        # Font type and size for the GUI text
        font = QFont('Helvetica', 9, QFont.Bold)

        # Master container that holds all other 'sub containers'
        master_layout = QVBoxLayout()
        
        # Planning group selection
        self.planning_group_combo = QComboBox(self)
        self.planning_group_combo.addItems(["interbotix_arm", "interbotix_gripper"])  
        # Add your planning groups here
        master_layout.addWidget(QLabel("Planning Group:"))
        master_layout.addWidget(self.planning_group_combo)
        
        self.planning_group_combo.currentTextChanged.connect(self.update_moveit_interface)
        
        # List of dynamically configurable parameters
        param_list = ['x [m]', 'y [m]', 'z [m]', 'roll [rad]', 'pitch [rad]', 'yaw [rad]']

        # List that contains the 'slider containers' (each one contains a parameter name, textbox,
        # and slider)
        slider_list = []

        # Create each 'slider container'. This includes:
        #   - a label showing one of the parameters in 'param_list'
        #   - a textbox showing the current slider value and which can also be edited
        #   - a slider that the user can drag to change a parameter's value
        for name in param_list:
            horizontal_layout = QHBoxLayout()
            vertical_layout = QVBoxLayout()
            label = QLabel(name)
            label.setFont(font)
            horizontal_layout.addWidget(label)
            display = QLineEdit('0.00')
            display.setAlignment(Qt.AlignRight)
            display.setFont(font)
            if '[m]' in name:
                display.setValidator(QDoubleValidator(-MAX_ARM_POS, MAX_ARM_POS, 2))
            else:
                display.setValidator(QDoubleValidator(-MAX_ROT_POS, MAX_ROT_POS, 2))
            horizontal_layout.addWidget(display)
            vertical_layout.addLayout(horizontal_layout)
            slider = QSlider(Qt.Horizontal)
            slider.setFont(font)
            slider.setRange(0, RANGE)
            slider.setValue(int(RANGE/2))
            vertical_layout.addWidget(slider)
            slider_list.append(vertical_layout)
            self.pose_map[name] = {'display': display, 'slider': slider}
            slider.valueChanged.connect(
                lambda event, name=name: self.on_slider_value_changed_one(name))
            display.editingFinished.connect(
                lambda name=name: self.on_text_value_changed_one(name))

        # Organize the six 'slider containers' into 3 rows where each row has two columns. The
        # first column is for end-effector position while the second column is for end-effector
        # orientation. Then add these 'rows' to the 'master' container
        num_rows = int(len(slider_list)/2)
        for i in range(num_rows):
            horizontal_layout = QHBoxLayout()
            slider_list[i].setContentsMargins(0, 0, 5, 0)
            slider_list[i+num_rows].setContentsMargins(5, 0, 0, 0)
            horizontal_layout.addLayout(slider_list[i])
            horizontal_layout.addLayout(slider_list[i+num_rows])
            master_layout.addLayout(horizontal_layout)

        # Next, create the 'planning' and 'execute' buttons...
        horizontal_button_layout = QHBoxLayout()

        self.plan_pose_button = QPushButton('Plan Pose', self)
        self.plan_pose_button.clicked.connect(self.plan_pose_event)
        horizontal_button_layout.addWidget(self.plan_pose_button)

        self.plan_position_button = QPushButton('Plan Position', self)
        self.plan_position_button.clicked.connect(self.plan_position_event)
        horizontal_button_layout.addWidget(self.plan_position_button)

        self.plan_orientation_button = QPushButton('Plan Orientation', self)
        self.plan_orientation_button.clicked.connect(self.plan_orientation_event)
        horizontal_button_layout.addWidget(self.plan_orientation_button)

        self.execute_button = QPushButton('Execute', self)
        self.execute_button.setEnabled(False)
        self.execute_button.clicked.connect(self.execute_event)
        horizontal_button_layout.addWidget(self.execute_button)
        
        # Adding new buttons for saving positions and path
        self.save_start_button = QPushButton('Save Start', self)
        #self.save_start_button.setEnabled(False)
        self.save_start_button.clicked.connect(self.save_start_position_event)
        horizontal_button_layout.addWidget(self.save_start_button)

        self.save_goal_button = QPushButton('Save Goal', self)
        self.save_goal_button.setEnabled(False)
        self.save_goal_button.clicked.connect(self.save_goal_position_event)
        horizontal_button_layout.addWidget(self.save_goal_button)

        self.save_path_button = QPushButton('Save Path', self)
        self.save_path_button.setEnabled(False)
        self.save_path_button.clicked.connect(self.save_path_event)
        horizontal_button_layout.addWidget(self.save_path_button)
        
        self.go_to_start_button = QPushButton('Go to Start', self)
        self.go_to_start_button.setEnabled(False)
        self.go_to_start_button.clicked.connect(self.go_to_start_event)
        horizontal_button_layout.addWidget(self.go_to_start_button)
        
        self.go_to_goal_button = QPushButton('Repeat path', self)
        self.go_to_goal_button.setEnabled(False)
        self.go_to_goal_button.clicked.connect(self.go_to_goal_event)
        horizontal_button_layout.addWidget(self.go_to_goal_button)
              
        self.grasp_button = QPushButton('Grasp object', self)
        self.grasp_button.clicked.connect(self.grasp_event)
        horizontal_button_layout.addWidget(self.grasp_button)
        
        self.release_button = QPushButton('Release object', self)
        self.release_button.clicked.connect(self.release_event)
        horizontal_button_layout.addWidget(self.release_button)
        
        self.elements_to_enable = (
            self.plan_pose_button,
            self.plan_position_button,
            self.plan_orientation_button,
            self.execute_button,
            self.save_path_button,
            self.save_goal_button,
            self.save_start_button,           
            
        )      
                
        if self.planning_group_combo.currentText() == "interbotix_arm":
          self.grasp_button.setEnabled(False) 
          self.release_button.setEnabled(False)  
        else :
          self.grasp_button.setEnabled(True) 
          self.release_button.setEnabled(True)
          self.enable_elements(False)

        master_layout.addLayout(horizontal_button_layout)

        # Finally, create the 'Reset' button (sets all slider bars and textboxes to '0.00') and the
        # status message label (tells user whether planning or execution attempt was successful)
        horizontal_message_layout = QHBoxLayout()
        self.reset_button = QPushButton('Reset', self)
        self.reset_button.clicked.connect(self.reset_event)
        horizontal_message_layout.addWidget(self.reset_button)
        horizontal_message_layout.addStretch(1)
        self.label = QLabel((
            'Welcome! Use this GUI to plan and execute ee poses, positions, and orientations. '
            'Note that not all combinations will work.'
        ))
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setFixedWidth(400)
        self.label.setFixedHeight(60)
        horizontal_message_layout.addWidget(self.label)
        horizontal_message_layout.addStretch(1)

        # Create the 'Clear' button (sends a service request to clear the MoveItVisual markers)
        self.clear_button = QPushButton('Clear Markers', self)
        self.clear_button.clicked.connect(self.clear_event)
        horizontal_message_layout.addWidget(self.clear_button)

        master_layout.addLayout(horizontal_message_layout)
        self.setLayout(master_layout)

        self.setSizePolicy(QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding))

        # Show the GUI!
        self.show()

    def closeEvent(self, _) -> bool:        
        self.executor.shutdown()
        self.destroy_node()
        self.thread.join()

    def enable_elements(self, enable: bool) -> None:        
        for element in self.elements_to_enable:
            element.setEnabled(enable)

    def on_slider_value_changed_one(self, name):        
        pose_info = self.pose_map[name]
        if '[m]' in name:
            ee_value = self.slider_value_to_position(pose_info['slider'].value())
        else:
            ee_value = self.slider_orientation_to_value(pose_info['slider'].value())
        pose_info['display'].setText(f'{ee_value:.2f}')

    def on_text_value_changed_one(self, name):        
        pose_info = self.pose_map[name]
        if '[m]' in name:
            slider_value = self.slider_position_to_value(pose_info['display'].text())
        else:
            slider_value = self.slider_value_to_orientation(pose_info['display'].text())
        pose_info['slider'].setValue(slider_value)

    def plan_pose_event(self, _):        
        self.plan(MoveItPlan.Request.CMD_PLAN_POSE)

    def plan_position_event(self, _):        
        self.plan(MoveItPlan.Request.CMD_PLAN_POSITION)

    def plan_orientation_event(self, _):        
        self.plan(MoveItPlan.Request.CMD_PLAN_ORIENTATION)
        
    def update_moveit_interface(self):
        selected_group = self.planning_group_combo.currentText()              
         
        self.label.setText('Changing planning group')               
        self.command.cmd = MoveItPlan.Request.CMD_CHANGE_PLANNING_GROUP
        self.command.new_planning_group = selected_group
        self.srv_moveit_plan()
    
    def plan(self, plan_type: int):        
        self.start_position = None
        self.goal_position = None
        self.path = [] 
        self.enable_elements(False)
        self.label.setText('Planning...')
        self.command.cmd = plan_type
        self.srv_moveit_plan()

    def execute_event(self, _):
        self.enable_elements(False)
        self.label.setText('Executing...')
        self.command.cmd = MoveItPlan.Request.CMD_EXECUTE
        self.srv_moveit_plan()
        
    def save_start_position_event(self, _):        
        try:
            # Create a Pose object from the current slider values
            pose = Pose()
            pose.position.x = self.slider_value_to_position(self.pose_map['x [m]']['slider'].value())
            pose.position.y = self.slider_value_to_position(self.pose_map['y [m]']['slider'].value())
            pose.position.z = self.slider_value_to_position(self.pose_map['z [m]']['slider'].value())
        
            roll = self.slider_orientation_to_value(self.pose_map['roll [rad]']['slider'].value())
            pitch = self.slider_orientation_to_value(self.pose_map['pitch [rad]']['slider'].value())
            yaw = self.slider_orientation_to_value(self.pose_map['yaw [rad]']['slider'].value())
        
            qx, qy, qz, qw = quaternion_from_euler(roll, pitch, yaw)
            pose.orientation = Quaternion(x=qx, y=qy, z=qz, w=qw)

            # Save the pose to the start_position attribute
            self.start_position = pose
            self.label.setText("Start position saved.")
        except Exception as e:
            self.label.setText(f"Failed to save start position: {str(e)}")
    
    def save_goal_position_event(self,_):
        
        if self.command.ee_pose:
           self.goal_position = self.command.ee_pose
           self.label.setText("Goal position saved.")
        else:
           self.label.setText("No goal position available to save.")
       
    def save_path_event(self,_):
        if self.planned_path:
            self.label.setText("half there")
            # Assuming planned_path is a list of poses
            self.path.extend(self.planned_path)
            self.label.setText("Planned path saved.")
            if self.start_position is not None and self.goal_position is not None and self.path:
               self.write_poses_to_file(self.start_position, self.goal_position, self.path)
               self.label.setText("Start, goal, and planned path saved to file.")
            else:
               self.label.setText("Start, goal, or planned path not set.")
        else:
            self.label.setText("No path available to save.")
        
        self.save_goal_button.setEnabled(False)
        self.save_path_button.setEnabled(False)
        self.save_start_button.setEnabled(False)
    
    def grasp_event(self):    
        self.grasp_button.setEnabled(False) 
        self.release_button.setEnabled(False)         
        self.label.setText('Grasping...')
        self.command.cmd = MoveItPlan.Request.CMD_GRIPPER_GRASP
        self.srv_moveit_plan()

    def release_event(self):        
        self.grasp_button.setEnabled(False) 
        self.release_button.setEnabled(False) 
        self.label.setText('Releasing...')
        self.command.cmd = MoveItPlan.Request.CMD_GRIPPER_RELEASE
        self.srv_moveit_plan()
    
    def go_to_start_event(self, _):  
        self.enable_elements(False)      
        self.label.setText('Going to start...')
        self.command.cmd = MoveItPlan.Request.CMD_EXECUTE_REVERSE
        self.srv_moveit_plan()           
                    
    def go_to_goal_event(self, _): 
        self.enable_elements(False)       
        self.label.setText('Repeating path...')
        self.command.cmd = MoveItPlan.Request.CMD_EXECUTE_AGAIN
        self.srv_moveit_plan()    

    def write_poses_to_file(self, start_pose, goal_pose, planned_path):
        """Write start pose, goal pose, and planned path to a file."""
        with open('/home/mridula/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_common_toolbox/interbotix_moveit_interface/files/saved_paths.txt', 'w') as file:  # Append mode
            file.write("Start Pose:\n")
            file.write(f"{start_pose}\n")  # Assuming start_pose is in a string format or can be converted
            file.write("Goal Pose:\n")
            file.write(f"{goal_pose}\n")  # Same assumption as above
            file.write("Planned Path:\n")
            for pose in planned_path:
               file.write(f"{pose}\n")  # Assuming each pose can be represented as a string
            file.write("\n") 
         
    
    def clear_event(self, _):       
        self.clear_markers_service.call_async(Empty.Request())

    def reset_event(self, _):        
        for value in self.pose_map.values():
            value['slider'].setValue(int(RANGE/2))
            
    def slider_value_to_position(self, slider):
        """
        Convert the raw slider value to a linear position in meters.

        :param slider: raw slider value out of 10,000
        """
        pctvalue = slider / float(RANGE)
        return -MAX_ARM_POS + 2*MAX_ARM_POS * pctvalue

    def slider_position_to_value(self, value):
        """
        Convert a position in meters to a raw slider value.

        :param value: current linear position [m]
        """
        pctvalue = (float(value) + MAX_ARM_POS)/(2*MAX_ARM_POS)
        return int(pctvalue * float(RANGE))

    def slider_orientation_to_value(self, slider):
        """
        Convert the raw slider value to an angular position in radians.

        :param slider: raw slider value out of 10,000
        """
        pctvalue = slider / float(RANGE)
        return -MAX_ROT_POS + 2*MAX_ROT_POS * pctvalue

    def slider_value_to_orientation(self, value):
        """
        Convert a position in radians to a raw slider value.

        :param value: current angular position [rad]
        """
        pctvalue = (float(value) + MAX_ROT_POS)/(2*MAX_ROT_POS)
        return int(pctvalue * float(RANGE))

    def srv_moveit_plan(self):        
        # If an 'Execute' request was received, call the service with the 'Execute' command
        if self.command.cmd == MoveItPlan.Request.CMD_EXECUTE:       
            execute_future: rclpy.Future = self.moveit_planner.call_async(self.command)
            execute_future.add_done_callback(self.execute_done_callback)                            
        elif self.command.cmd == MoveItPlan.Request.CMD_EXECUTE_REVERSE:       
            execute_future: rclpy.Future = self.moveit_planner.call_async(self.command)
            execute_future.add_done_callback(self.execute_done_callback)              
        elif self.command.cmd == MoveItPlan.Request.CMD_EXECUTE_AGAIN:       
            execute_future: rclpy.Future = self.moveit_planner.call_async(self.command)
            execute_future.add_done_callback(self.execute_done_callback)              
        elif self.command.cmd == MoveItPlan.Request.CMD_CHANGE_PLANNING_GROUP:       
            change_group: rclpy.Future = self.moveit_planner.call_async(self.command)
            change_group.add_done_callback(self.group_change_done_callback)          
        elif self.command.cmd in [MoveItPlan.Request.CMD_GRIPPER_GRASP, MoveItPlan.Request.CMD_GRIPPER_RELEASE]:
            gripper_future: rclpy.Future = self.moveit_planner.call_async(self.command)
            gripper_future.add_done_callback(self.gripper_done_callback)           
        elif self.command.cmd is not MoveItPlan.Request.CMD_NONE:
            pose = Pose()
            roll = self.slider_orientation_to_value(
                self.pose_map['roll [rad]']['slider'].value()
            )
            pitch = self.slider_orientation_to_value(
                self.pose_map['pitch [rad]']['slider'].value()
            )
            yaw = self.slider_orientation_to_value(
                self.pose_map['yaw [rad]']['slider'].value()
            )
            pose.position.x = self.slider_value_to_position(
                self.pose_map['x [m]']['slider'].value()
            )
            pose.position.y = self.slider_value_to_position(
                self.pose_map['y [m]']['slider'].value()
            )
            pose.position.z = self.slider_value_to_position(
                self.pose_map['z [m]']['slider'].value()
            )
            qx, qy, qz, qw = quaternion_from_euler(roll, pitch, yaw)
            pose.orientation = Quaternion(x=qx, y=qy, z=qz, w=qw)
            self.get_logger().info((
                'Desired end-effector pose: '
                f'x[m]: {pose.position.x:.2f}, y[m]: {pose.position.y:.2f}, '
                f'z[m] {pose.position.z:.2f}, roll[rad]: {roll:.2f}, '
                f'pitch[rad]: {pitch:.2f}, yaw[rad]: {yaw:.2f}.'
            ))
            self.command.ee_pose = pose
            planner_future: rclpy.Future = self.moveit_planner.call_async(self.command)
            planner_future.add_done_callback(self.planner_done_callback)
        # Clear the command once it was acted upon
        #self.command.cmd = MoveItPlan.Request.CMD_NONE

    def planner_done_callback(self, planner_future: rclpy.Future):
        planner_resp: MoveItPlan.Response = planner_future.result()
        self.get_logger().info(planner_resp.msg.data)
        
        # Update the message status label       
        if planner_resp.success:
           self.planned_path = [list(point.positions) for point in planner_resp.trajectory.joint_trajectory.points]
        else:
           self.label.setText(" no planned Path")       
        self.label.setText(planner_resp.msg.data)
        self.enable_elements(True)        
        # Reveal the 'Execute' button if successful plan was achieved
        if not planner_resp.success:
            self.execute_button.setEnabled(False)
            self.save_goal_button.setEnabled(False)
            self.save_start_button.setEnabled(False)
            self.save_path_button.setEnabled(False)            
        self.command.cmd = MoveItPlan.Request.CMD_NONE
    def execute_done_callback(self, execute_future: rclpy.Future):
        execute_resp: MoveItPlan.Response = execute_future.result()
        self.get_logger().info(execute_resp.msg.data)
        # Update the message status label
        self.label.setText(execute_resp.msg.data)
        # Disable the 'Execute' button until another successful planning request was achieved    
        self.enable_elements(True) 
        self.execute_button.setEnabled(False)   
        if execute_resp.success:          
          if self.command.cmd == MoveItPlan.Request.CMD_EXECUTE:              
             self.go_to_goal_button.setEnabled(False)
             self.go_to_start_button.setEnabled(True)
          elif self.command.cmd == MoveItPlan.Request.CMD_EXECUTE_REVERSE: 
             self.go_to_start_button.setEnabled(False)             
             self.go_to_goal_button.setEnabled(True)  
          elif self.command.cmd == MoveItPlan.Request.CMD_EXECUTE_AGAIN: 
             self.go_to_goal_button.setEnabled(False)                 
             self.go_to_start_button.setEnabled(True)                
        
        self.command.cmd = MoveItPlan.Request.CMD_NONE
        
    def group_change_done_callback(self, group_future: rclpy.Future):
        group_resp: MoveItPlan.Response = group_future.result()
        self.get_logger().info(group_resp.msg.data)
        # Update the message status label
        self.label.setText(group_resp.msg.data)         
        if self.planning_group_combo.currentText() == "interbotix_arm":
          self.grasp_button.setEnabled(False) 
          self.release_button.setEnabled(False)  
          self.enable_elements(True) 
          self.execute_button.setEnabled(False)
          #self.go_to_start_button.setEnabled(True)    
          #self.go_to_goal_button.setEnabled(True) 
        else :
          self.grasp_button.setEnabled(True) 
          self.release_button.setEnabled(True)
          self.enable_elements(False)          
          #self.go_to_start_button.setEnabled(False)    
          #self.go_to_goal_button.setEnabled(False) 
        self.command.cmd = MoveItPlan.Request.CMD_NONE
        
    def gripper_done_callback(self, gripper_future: rclpy.Future):
        gripper_resp: MoveItPlan.Response = gripper_future.result()
        self.get_logger().info(gripper_resp.msg.data)
        # Update the message status label
        self.label.setText(gripper_resp.msg.data)      
        if self.command.cmd == MoveItPlan.Request.CMD_GRIPPER_GRASP:            
           self.release_button.setEnabled(True)            
        elif self.command.cmd == MoveItPlan.Request.CMD_GRIPPER_RELEASE:      
           self.grasp_button.setEnabled(True)                           
        self.command.cmd = MoveItPlan.Request.CMD_NONE 

if __name__ == '__main__':
    app = QApplication(sys.argv)
    rclpy.init()
    ex = MultiThreadedExecutor()
    thread_spin = Thread(target=ex.spin)
    moveit_gui = MoveItGUIInterface(thread_spin)
    ex.add_node(moveit_gui)
    thread_spin.start()
    # Only kill the program at node shutdown
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    sys.exit(app.exec())
